# Generated by Django 4.0.6 on 2022-07-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0002_tasktype_remove_task_type_task_types_tasktype_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='types',
            new_name='types_old',
        ),
    ]
