# Generated by Django 4.0.6 on 2022-07-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0003_rename_types_task_types_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='types_old',
            field=models.ManyToManyField(blank=True, related_name='old_tasks', through='trecker.TaskType', to='trecker.type'),
        ),
    ]
