# Generated by Django 4.0.6 on 2022-07-19 09:02

from django.db import migrations, models
import trecker.validate


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0007_remove_task_types_old_delete_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=30, validators=[trecker.validate.summary_max_10_len], verbose_name='Заголовок'),
        ),
    ]
