# Generated by Django 4.0.6 on 2022-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0008_alter_task_description_alter_task_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование проекта')),
                ('description', models.TextField(max_length=500, verbose_name='Описание проекта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'db_table': 'projects',
            },
        ),
    ]
