# Generated by Django 4.0.6 on 2022-07-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0010_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
