# Generated by Django 4.0.6 on 2022-07-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0011_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taskss', to='trecker.project', verbose_name='Проект'),
        ),
    ]
