# Generated by Django 4.0.6 on 2022-08-12 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trecker', '0012_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
