# Generated by Django 4.0.6 on 2022-08-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0013_project_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Users',
            new_name='User',
        ),
    ]
