# Generated by Django 4.0.6 on 2022-08-15 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trecker', '0017_alter_project_user_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='User',
            field=models.ManyToManyField(default=1, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='task',
            name='User',
            field=models.ManyToManyField(default=1, related_name='taskes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
