# Generated by Django 4.0.6 on 2022-08-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0018_alter_project_user_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='User',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='User',
            new_name='author',
        ),
    ]
