# Generated by Django 4.0.6 on 2022-08-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0019_rename_user_project_author_rename_user_task_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
