# Generated by Django 4.0.6 on 2022-08-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trecker', '0020_rename_author_project_users_remove_task_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_users_to_projects', 'Добавить юзеров в проект')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
